// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace App.Sdk.Models {
    public class Query : IParsable {
        /// <summary>The additionalDataProperty property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public Query_additionalData? AdditionalDataProperty { get; set; }
#nullable restore
#else
        public Query_additionalData AdditionalDataProperty { get; set; }
#endif
        /// <summary>The displayText property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayText { get; private set; }
#nullable restore
#else
        public string DisplayText { get; private set; }
#endif
        /// <summary>The searchLink property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SearchLink { get; private set; }
#nullable restore
#else
        public string SearchLink { get; private set; }
#endif
        /// <summary>The text property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Text { get; set; }
#nullable restore
#else
        public string Text { get; set; }
#endif
        /// <summary>The thumbnail property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ImageObject? Thumbnail { get; set; }
#nullable restore
#else
        public ImageObject Thumbnail { get; set; }
#endif
        /// <summary>The webSearchUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WebSearchUrl { get; private set; }
#nullable restore
#else
        public string WebSearchUrl { get; private set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="Query"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static Query CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new Query();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"additionalData", n => { AdditionalDataProperty = n.GetObjectValue<Query_additionalData>(Query_additionalData.CreateFromDiscriminatorValue); } },
                {"displayText", n => { DisplayText = n.GetStringValue(); } },
                {"searchLink", n => { SearchLink = n.GetStringValue(); } },
                {"text", n => { Text = n.GetStringValue(); } },
                {"thumbnail", n => { Thumbnail = n.GetObjectValue<ImageObject>(ImageObject.CreateFromDiscriminatorValue); } },
                {"webSearchUrl", n => { WebSearchUrl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<Query_additionalData>("additionalData", AdditionalDataProperty);
            writer.WriteStringValue("text", Text);
            writer.WriteObjectValue<ImageObject>("thumbnail", Thumbnail);
        }
    }
}
