// <auto-generated/>
using App.Client.Cli.My;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Cli.Commons.IO;
using Microsoft.Kiota.Cli.Commons;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using System.Collections.Generic;
using System.CommandLine;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System;
namespace App.Client.Cli {
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    public class AppClientCli : BaseCliRequestBuilder {
        /// <summary>
        /// The my property
        /// </summary>
        /// <returns>A <see cref="Command"/></returns>
        public Command BuildMyNavCommand() {
            var command = new Command("my");
            command.Description = "The my property";
            var builder = new MyRequestBuilder(PathParameters);
            var nonExecCommands = new List<Command>();
            nonExecCommands.Add(builder.BuildTrendingNavCommand());
            foreach (var cmd in nonExecCommands)
            {
                command.AddCommand(cmd);
            }
            return command;
        }
        /// <summary>
        /// Instantiates a new <see cref="AppClientCli"/> and sets the default values.
        /// </summary>
        /// <returns>A <see cref="Command"/></returns>
        public Command BuildRootCommand() {
            var command = new RootCommand();
            command.Description = "Instantiates a new AppClientCli and sets the default values.";
            command.AddCommand(BuildMyNavCommand());
            return command;
        }
        /// <summary>
        /// Instantiates a new <see cref="AppClientCli"/> and sets the default values.
        /// </summary>
        public AppClientCli() : base("{+baseurl}", new Dictionary<string, object>()) {
        }
    }
}
