// <auto-generated/>
using App.Client.Sdk.My.Trending;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace App.Client.Sdk.My {
    /// <summary>
    /// Builds and executes requests for operations under \my
    /// </summary>
    public class MyRequestBuilder : BaseRequestBuilder {
        /// <summary>The trending property</summary>
        public TrendingRequestBuilder Trending { get =>
            new TrendingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="MyRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MyRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/my", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new <see cref="MyRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MyRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/my", rawUrl) {
        }
    }
}
