// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NewsSearch.Sdk.News.Trendingtopics {
    public enum GetSafeSearchQueryParameterType {
        [EnumMember(Value = "Off")]
        Off,
        [EnumMember(Value = "Moderate")]
        Moderate,
        [EnumMember(Value = "Strict")]
        Strict,
    }
}
