// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NewsSearch.Sdk.News.Trendingtopics {
    public enum GetTextFormatQueryParameterType {
        [EnumMember(Value = "Raw")]
        Raw,
        [EnumMember(Value = "Html")]
        Html,
    }
}
