// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NewsSearch.Sdk.Models {
    /// <summary>The error code that further helps to identify the error.</summary>
    public enum Error_subCode {
        [EnumMember(Value = "UnexpectedError")]
        UnexpectedError,
        [EnumMember(Value = "ResourceError")]
        ResourceError,
        [EnumMember(Value = "NotImplemented")]
        NotImplemented,
        [EnumMember(Value = "ParameterMissing")]
        ParameterMissing,
        [EnumMember(Value = "ParameterInvalidValue")]
        ParameterInvalidValue,
        [EnumMember(Value = "HttpNotAllowed")]
        HttpNotAllowed,
        [EnumMember(Value = "Blocked")]
        Blocked,
        [EnumMember(Value = "AuthorizationMissing")]
        AuthorizationMissing,
        [EnumMember(Value = "AuthorizationRedundancy")]
        AuthorizationRedundancy,
        [EnumMember(Value = "AuthorizationDisabled")]
        AuthorizationDisabled,
        [EnumMember(Value = "AuthorizationExpired")]
        AuthorizationExpired,
    }
}
