// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NewsSearch.Sdk.Models {
    /// <summary>The error code that identifies the category of error.</summary>
    public enum Error_code {
        [EnumMember(Value = "None")]
        None,
        [EnumMember(Value = "ServerError")]
        ServerError,
        [EnumMember(Value = "InvalidRequest")]
        InvalidRequest,
        [EnumMember(Value = "RateLimitExceeded")]
        RateLimitExceeded,
        [EnumMember(Value = "InvalidAuthorization")]
        InvalidAuthorization,
        [EnumMember(Value = "InsufficientAuthorization")]
        InsufficientAuthorization,
    }
}
