// <auto-generated/>
using Microsoft.Kiota.Abstractions;
using NewsSearch.Sdk.News.Trendingtopics;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace NewsSearch.Sdk.News {
    /// <summary>
    /// Builds and executes requests for operations under \news
    /// </summary>
    public class NewsRequestBuilder : BaseRequestBuilder {
        /// <summary>The trendingtopics property</summary>
        public TrendingtopicsRequestBuilder Trendingtopics { get =>
            new TrendingtopicsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="NewsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NewsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/news", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new <see cref="NewsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NewsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/news", rawUrl) {
        }
    }
}
