// <auto-generated/>
using App.Client.Cli.My.Trending;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Cli.Commons.IO;
using Microsoft.Kiota.Cli.Commons;
using System.Collections.Generic;
using System.CommandLine;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System;
namespace App.Client.Cli.My {
    /// <summary>
    /// Builds and executes requests for operations under \my
    /// </summary>
    public class MyRequestBuilder : BaseCliRequestBuilder {
        /// <summary>
        /// The trending property
        /// </summary>
        /// <returns>A <see cref="Command"/></returns>
        public Command BuildTrendingNavCommand() {
            var command = new Command("trending");
            command.Description = "The trending property";
            var builder = new TrendingRequestBuilder(PathParameters);
            var execCommands = new List<Command>();
            execCommands.Add(builder.BuildGetCommand());
            foreach (var cmd in execCommands)
            {
                command.AddCommand(cmd);
            }
            return command;
        }
        /// <summary>
        /// Instantiates a new <see cref="MyRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        public MyRequestBuilder(Dictionary<string, object> pathParameters) : base("{+baseurl}/my", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new <see cref="MyRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public MyRequestBuilder(string rawUrl) : base("{+baseurl}/my", rawUrl) {
        }
    }
}
